# Generated by Django 5.2 on 2025-04-12 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('saida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
